FROM nginx
# COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/

# # Build 
# docker build -f Dockerfile -t testwebserver .

# Run
# docker run --name=testwebserver --restart unless-stopped --network host -d -t testwebserver